AllCops:
  Exclude:
    - 'bin/**'
    - 'config/routes.rb'
    - 'test/**'

Rails:
  Enabled: true
Rails/HasAndBelongsToMany:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/LeadingCommentSpace:
  Enabled: false
Metrics/MethodLength:
  Max: 20

Style/IndentArray:
  Exclude:
    - 'test/controllers/documents_search_controller_test.rb'
