AllCops:
  Exclude:
    - 'bin/**'
    - 'config/routes.rb'

Rails:
  Enabled: true
Rails/HasAndBelongsToMany:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/LeadingCommentSpace:
  Enabled: false
