AllCops:
  Exclude:
    - 'bin/**'

Rails:
  Enabled: true
Metrics/LineLength:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/LeadingCommentSpace:
  Enabled: false
