sudo: required

language: ruby

services:
  - docker

before_install:
  - docker-compose build

install: ls

script:
  - docker-compose run api rake static_analysis
  - docker-compose run api rake test
