version: '2.0'

services:
  mongodb:
    image: mongo:3.2
    # TODO: mongod --smallfiles?
    command: mongod
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo:/data
  
  website:
    depends_on:
      - 'mongodb'
    build: .
    ports:
      - '3000:3000'
    environment:
      - DOCKERIZED=true
    volumes:
      - '.:/archivist'
