development:
  clients:
    default:
      database: archivist-api_development
      hosts:
        - mongodb:27017
test:
  clients:
    default:
      database: archivist-api_test
      hosts:
        - mongodb:27017
