development:
  clients:
    default:
      database: archivist_development
      hosts:
        - mongodb:27017
test:
  clients:
    default:
      database: archivist_test
      hosts:
        - mongodb:27017
