development:
  clients:
    default:
      database: archivist-api_development
      hosts:
        - mongodb:27017
  options:
    preload_models: true
    raise_not_found_error: false
test:
  clients:
    default:
      database: archivist-api_test
      hosts:
        - mongodb:27017
  options:
    preload_models: true
